### ISSUE TITLE
Encapsulate CI tasks in Github Actions for PUBLIC repos

### ISSUE THREAD

**Issue by kaisermann** [vtex/typescript#15]
We've decided to use [Github Actions](https://github.com/features/actions) in our favor (it's free ✨) so we can automate linting, testing and other trivial tasks. While we can add a `.github/workflows/ci.yml` with all the tasks configuration in each project, it'd be nice if we could encapsulate them in small bundled actions.

Tasks to consider:
- Lint
- Run tests
- Outdated eslint config (upgrade message)
- Missing changelog entry

Thread on slack: https://vtex.slack.com/archives/CM2V0PELD/p1579012577088900

Edit: 

Just making clear that this is related to **_public_** repositories. Private ones have more limitations as @guilhermebruzzi stated on the above slack thread. For private repos the solution will be a self-hosted one that we'll likely build at some point if the VPs agree: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/about-self-hosted-runners

**Comment by Lurian** [comment]
The inStore team uses [github actions for running e2e tests in the CI](https://github.com/vtex/checkout-instore/actions?query=workflow%3A%22Cypress+parallel+tests%22)

We are still validating this approach...

**Comment by kaisermann** [comment]
@Lurian Will definitely check it out! For now, I'm thinking about something similar to what I did in `builder-hub`: https://github.com/vtex/builder-hub/pull/808/checks?check_run_id=354966570

Simple linting (with comments on the file lines) and unit testing.

**Comment by kaisermann** [comment]
Done 😁
