### ISSUE TITLE
Prefer `literal types` instead `enum`

### ISSUE THREAD

**Issue by gtkatakura** [vtex/typescript#60]
### UPDATED - 30/11/2020

This issue shows the bad parts of enum and how the default approach when using enum enables some potential problems, but I just want to remember that when you really need support for bitwise operators (micro-optimizations or save database space) or when you have a literal type shared among multiple codes, maybe you prefer to use const enum with string values to enable better refactoring features from your code editor. Most of the problems are about **enum with number values** and because enum has number values by default, so it enables the bad parts of an enum by default.

---

**Is your feature request related to a problem? Please describe.**
Today we have no rules related to enum, even though literal types and enums in TS end up solving the same problem in many cases and the enum has some trade-offs that in most cases literal types seem to solve the problem better. See:

### Enum infers sequential numbers automatically when initializers are omitted

```ts
enum Status {
  Open, // infer 0
  Closed, // infer 1
}

declare const updateStatus: (value: Status) => void

updateStatus(0) // same as updateStatus(Status.Open)
```

The problem with this approach is that if new values are declared without following the existing order, if the value of the enum has been saved in an external resource, we will have inconsistencies between the saved value and the new representation, example:

```ts
enum Status {
  Idle, // new value
  Open,
  Closed,
}

type Resource = { status: Status }

// previous have { status: Status.Open }, which is { status: 0 }
// but { status: 0 } maps to { status: Status.Idle } now
const resource = findResource(id)

resource.status === Idle // returns true
```

And removing an option from the enum is not possible unless it is the last option in the enum, otherwise, the order will break as well.

### Enum has poor interoperability with numbers and strings

```ts
enum Status {
  Open, // infer 0
  Closed, // infer 1
}

declare const updateStatus: (value: Status) => void

updateStatus(12345) // accepts any number, so accepts invalid values
// also, this is necessary to support bitwise operator, but most of the cases
// we don't need bitwise operators, so this only enables the possibility of pass
// invalid values

const text = Status[Status.Open] // returns `string`, why not a literal type `Open`?
```

```ts
enum Status {
  Open = 'open',
  Closed = 'closed',
}

declare const updateStatus: (value: Status) => void

updateStatus('open') // invalid code, needs manual mapping between 'open' and Status.Open
```

### Literal types are simpler than enums with string values

```ts
enum Status {
  Open = 'open',
  Closed = 'closed',
}

type Status = 'open' | 'closed'
```

### Enum generates a lookup object, increasing the bundle size and memory allocation

```ts
enum Status {
  Open = 'open',
  Closed = 'closed',
}
// =======

// generated js code
'use strict'
var Status
;(function (Status) {
  Status['Open'] = 'open'
  Status['Closed'] = 'closed'
})(Status || (Status = {}))
```

### There is a scenario that the enum is useful

That's when we need to use less disk space from the database (or something similar), so saving numbers would help with this and we also need denote many states at the same time (using bitwise operators).

```ts
enum Actions {
  None = 0,
  Create = 1 << 0,
  Update = 1 << 1,
  Delete = 1 << 2,
}
```

But this is an optimization case only, ideally saving a JSON array would solve, so it seems to be a very unusual scenario.

**Describe the solution you'd like**
A rule to disable the use of enum and recommend the use of literal types.

**Describe alternatives you've considered**
A rule to force the use of initializers, to at least mitigate part of the problems. It would also be good for the lint to encourage the use of string values instead of number values.

**Comment by kaisermann** [comment]
I'm highly inclined to agree with banning the usage of `enum`. This is a recurrent topic at VTEX's front-end chapter meeting (cc @salesfelipe) and has already caused some damage with the automatically generated typings for IO apps. 

If we decide to ban enum, we could leverage the [`no-restricted-syntax`](https://eslint.org/docs/rules/no-restricted-syntax) rule. See https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#how-can-i-ban-specific-language-feature.

In my opinion, if we follow this path, the only big issue is that we're going to be introducing a somewhat breaking-change. Can we guarantee that refactoring `enum`s  to literal `type`s is going to be a easy process?

**Comment by gtkatakura** [comment]
What can cause the most trouble is if enum was used with numeric values and saved in databases. Also in cases of manual mapping between string values to enum, but to resolve it would basically be to take and use direct string values.

**Comment by salesfelipe** [comment]
I agree with banning it :)

**Comment by kaisermann** [comment]
Added in `eslint-config-vtex-react@6.7.0`, `eslint-config-vtex@12.7.0` and `eslint-plugin-vtex@1.2.0`

**Comment by rvitorper** [comment]
I think the point of using enums is not to use literals or hanging strings and numbers. For example, the following example is a little bit misleading:
```
enum Status {
  Open, // infer 0
  Closed, // infer 1
}

declare const updateStatus: (value: Status) => void

updateStatus(0) // same as updateStatus(Status.Open)
```

Why would you pass `0`? The whole purpose of using the enum is to pass `Status.Open` and not `0`.

Also, this example is misleading:
```
enum Status {
  Idle, // new value
  Open,
  Closed,
}

type Resource = { status: Status }

const resource = findResource(id) // previous have { status: Status.Open }

resource.status === Idle // returns true
```

What exactly does `findResource` return? Does it return a number or an enum value? For instance, the following `findResource` would return the expected result:

```
const findResource = () => Status.Idle;
```

Whereas this one would not:

```
const findResource = () => Status.Open;
```

This another example is misleading as well:

```
const text = Status[Status.Open] // returns `string`, why not a literal type `Open`?
```

There is a simpler alternative to setting text to `Open`:

```
const text = Status.Open // that's it
```

This case, for instance, is an over-simplified statement:

```
enum Status {
  Open = 'open',
  Closed = 'closed',
}

type Status = 'open' | 'closed'
```

Oftentimes you don't want to use types with strings for a simple reason: they might change. For example:

```
type FeatureFlagValues = "HOMEPAGE_TITLE" | "HOMEPAGE_LISTING_ORDER" | "BANNER_INTERLEAVING"; // Bad usage of types

// const getVariant = (flag: string) => axios.get(`FF_API_ENDPOINT/${flag}`);
getVariant("HOMEPAGE_TITLE") // If this flag changes to another one, for any reason, you will be in trouble, as you will have to change in lots of places
```

Now, if you used an enum:

```
enum FeatureFlagValues {
  HOMEPAGE_TITLE = "HOMEPAGE_TITLE",
  HOMEPAGE_LISTING_ORDER = "HOMEPAGE_LISTING_ORDER",
  BANNER_INTERLEAVING = "BANNER_INTERLEAVING"
}
// const getVariant = (flag: FeatureFlagValues) => axios.get(`FF_API_ENDPOINT/${flag}`);
getVariant(FeatureFlagValues.HOMEPAGE_TITLE); // If you change the value of HOMEPAGE_TITLE, no problem at all.
```

In the case before, even if you remove one value, you won't have any surprises, because it will generate a compilation error, rather than a runtime error.

But the real strength of enums lies when you use them with Records, just like the following example:

```
enum DisplayStrategy {
  FOOTER_AND_HEADER,
  SIDE_MENU
}

const displayStrategyToComponentLink: Record<DisplayStrategy, React.Component> = {
  [DisplayStrategy.FOOTER_AND_HEADER]: FooterAndHeader,
  [DisplayStrategy.SIDE_MENU]: SideMenu
}
```

If you ever remove an entry of the enum, it will return a compile-time error, not some shady runtime error. Also, if you add a new entry to the enum, it will force you to implement the link between the strategy and the component at the map - returning a compile-time error rather than a runtime error. This saves A LOT of time, just because it is a compile-time error instead of the runtime error. This helps with forgetting the places where you have to add the required items.

Regarding the point `Enum generates a lookup object, increasing the bundle size and memory allocation`, do we currently have a benchmark of how much does it increase the bundle size? I think bundle size is a good point, but the greatest offenders oftentimes are not enums - just using `lodash`, for instance, increases the bundle size by a lot.

**Comment by gtkatakura** [comment]
> Why would you pass 0? The whole purpose of using the enum is to pass Status.Open and not 0.

Yes, the purpose is to use `Status.Open`, but the point is TypeScript permits you to use any number as a valid value for the type check. So `you can`, when TypeScript should type check to not permit this. It is a specific problem about enum as number values. When you use literal types, you can't pass an invalid number. Also, enum as string values don't have this problem.

---
> What exactly does findResource return? Does it return a number or an enum value? For instance, the following findResource would return the expected result:

The example is about use enum without explicit values, so when enum infers sequential numbers, you have problems when saving this data into external data sources when adding/removing new values to Status. Examples (can run [version 1 here](https://www.typescriptlang.org/play?#code/KYOwrgtgBAygLgQzmAzlA3gWAFBSgeQAdQAaHPAYQBsB7FYAEzOwF8cc4BPYqAJWBQ0wAJwDGwKAF4MUAJYMAXFBRxhskAHMSyxMhRL4SVFDbYcAMzAhRcWTRDKEAN2D9BI8QAphAoWOBKbn7iAJQY5FC0oghU8DTCCBrAAHT0cACScMAQ3r4eKfLaAFIw+AByqarqGrLmnLnu-iEhOKY4APTtUABGwNGoEoZ6UAAWCGjgEL3CUONQTjFgwNpwI7JoAO6yVFSOLlAADHIgcDRQqxIMSAjd48uRsgDWATgozq55-p7ocopQAOSiBgHABsogALAB2boAWnBAGZ4eY4d1UTCEGCQTCAKzdeEATnBIPBwFJ8Mh-20KiM+lgulQySIoBMISAA) and [version 2 here](https://www.typescriptlang.org/play?#code/KYOwrgtgBAygLgQzmAzlA3gWAFBSgSQBMAbYAGigHpKoRgB3KANwWLGBzwHkAHUMzlADCxAPYpghAdgC+OHHACefKACVgKUWABOAY2BQAvBigBLQgC4oKONtMgA5hRtJUV+K7RzsOAGZgQXThTURAoX3tCdU0dfQAKcytorT1gAG0AcnMMgF0ASiSNFP0MQW1gZG0wgCkYLgA5ADoeBG0JOLFdVnhRbQQHYEaBuHw4YAgEwjyAQjycbxxdUJsocpjUo3DI5NjgOIzdQgAGADZdABYAdgAjAFpzgGYH33vrt9uEM5PbgFZrh4AnOcTudgGCHpcMnMfNg1sVBi5kGhDCjYIgkY0iKQqDRypUQGhbOwgA))

```ts
// version 1 of your code
enum Status {
  Open,
  Closed,
}

type Resource = { id: string, status: Status }

function saveResource(resource: Resource) {
  localStorage.setItem(resource.id, JSON.stringify(resource))
}

// because Status has number as value, this will save 0 into the database, like:
saveResource({ id: 'cd06c47b-433f-4bbb-a6c6-5b39464eee37', status: Status.Open })

// version 2 of your code, now you added Idle to your Status
enum Status {
  Idle, // new value
  Open,
  Closed,
}

type Resource = { id: string, status: Status }

function findResource(id: Resource['id']): Resource {
  return JSON.parse(localStorage.getItem(id)!)
}

const resource = findResource('cd06c47b-433f-4bbb-a6c6-5b39464eee37')

resource.status === Status.Idle // returns true
```

---

> There is a simpler alternative to setting text to Open:
> ```
> const text = Status.Open // that's it
> ```

This doesn't work, the value is `0` if you use `Status.Open` of the example will be `0` the value. The example is about getting the `key` value appropriately typed.

```ts
enum Status {
  Open, // infer 0
  Closed, // infer 1
}

const value = Status.Open // equals to 0
const text = Status[Status.Open]
```

---

> This case, for instance, is an over-simplified statement:
> Oftentimes you don't want to use types with strings for a simple reason: they might change. For example:

I wrote an update on 30/11/2020 about these cases, I agree with you about using enum when you have a lot of places referring to the value.

> when you have a literal type shared among multiple codes, maybe you prefer to use const enum with string values to enable better refactoring features from your code editor. Most of the problems are about enum with number values and because enum has number values by default, so it enables the bad parts of an enum by default.

---

> Enum generates a lookup object, increasing the bundle size and memory allocation

It is more an extra point, I don't think this is the more important issue about enums. The most important issue is about using numbers as values or using the implicit values mecanhism. In the section `Describe alternatives you've considered` I talk more about this.

> It would also be good for the lint to encourage the use of string values instead of number values. (I talking about values of enum here)

**Comment by kaisermann** [comment]
> A rule to force the use of initializers, to at least mitigate part of the problems. It would also be good for the lint to encourage the use of string values instead of number values.

Just for the record, that happened: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/prefer-enum-initializers.md

**Comment by gtkatakura** [comment]
This example has problems with type because It use string instead the created literal type.

```ts
type FeatureFlagValues = "HOMEPAGE_TITLE" | "HOMEPAGE_LISTING_ORDER" | "BANNER_INTERLEAVING"

// const getVariant = (flag: FeatureFlagValues) => axios.get(`FF_API_ENDPOINT/${flag}`);
getVariant("HOMEPAGE_TITLE")
```

Also, you can use literal types with records, you will have the same compiler error using literal types.
